function stats_bc = compute_cyclicality_stats(detrended_series, is_data)
% Compute cyclicality stats based on detrended time series

if is_data==1
    detrended_name = 'hpf_dev';
    time_range = year(detrended_series.date)>=1997 & year(detrended_series.date)<=2016; 
    detrended_series = detrended_series(time_range, :);
else
    detrended_name = 'dev';
end

series = {...
    'lngdp', ...
    'alp', ...
    'lp_wgt', ...
    'lp_avg', ...
    'lp_opm', ...
    'u', ...
    'ue', ...
    'eu', ...
    'ee', ...
    'lnu', ...
    'lnv', ...
    'lnue', ...
    'lneu', ...
    'lnee', ...
    'lnfirms', ...
    % 'lnentr', ...
    % 'lnexit', ...
    };

% series = strcat(series, '_', detrended_name);

stats = {...
    'std', ...
    'acl', ...
    'cor', ...
    'min', ...
    'max', ...
    };

n_series = length(series);
n_stats = length(stats);

stats_bc = array2table(zeros(n_series, n_stats));

stats_bc.Properties.RowNames = series;
stats_bc.Properties.VariableNames = stats;

for j = 1:n_series

    y = detrended_series{:, strcat(series(j), '_', detrended_name)};
    
    stats_bc.std(j) = std(y, 'omitnan');
    stats_bc.cor(j) = corr_xy(detrended_series{:, ['lngdp_', detrended_name]}, y);
    stats_bc.min(j) = min(y, [], 'omitnan');
    stats_bc.max(j) = max(y, [], 'omitnan');

    y_lag = detrended_series{1:end-1, strcat(series(j), '_', detrended_name)};
    y_now = detrended_series{2:end, strcat(series(j), '_', detrended_name)};

    stats_bc.acl(j) = corr_xy(y_lag, y_now);
    
    
end


