
close all;
clearvars;
clc;

project_dir = ['..' filesep '..'];
timeseries_dir = [project_dir filesep 'data' filesep 'time_series'];

detrended_dir = [timeseries_dir filesep 'detrended'];
if ~exist(detrended_dir, 'dir')
    mkdir(detrended_dir);
end

y_series = readtable([timeseries_dir filesep 'detrended/yearly_series.csv']);

% Set up monthly index
date = y_series.date(1) + calmonths(0:12*(height(y_series) - 1));
date = transpose(dateshift(date,'end','month'));

monthly_series = table(date);

% Spline interpolation
time_series = {...
    'lngdp',...
    'lnalp',...
    'lnu',...
    'lnv',...
    'lnue',...
    'lneu',...
    'lnee',...
    'lnw',...
    'alp',...
    'u',...
    'ue',...
    'ee',...
    'eu',...
    'lp_wgt',...
    'lp_avg',...
    'lp_opm',...
    'ec_wgt',...
    'ec_avg',...
    'ec_opm',...
    'lnfirms',...
    'lnentr',...
    'lnexit',...
    };

for j = 1:length(time_series)
    
    ts_name = strcat(time_series(j),'_hpf_dev');

    ts_t = y_series{~isnan(y_series{:,ts_name}),'date'};
    ts_y = y_series{~isnan(y_series{:,ts_name}),ts_name};

    ts_itp = interp1(ts_t,ts_y,date,'spline',NaN);
    
    monthly_series{:,ts_name} = ts_itp;
end

% Save monthly interpolated data
writetable(monthly_series,[timeseries_dir filesep 'detrended/monthly_series.csv']);

